# Singleton service factory configuration/IoC injection
singletons:

- javax.sql.DataSource:
  - com.zaxxer.hikari.HikariDataSource:
      jdbcUrl: "jdbc:postgresql://localhost:5432/petstore"
      username: postgres
      password: ""
      maximumPoolSize: 95
  # MapConsumerRepository implements CustomerRepository with no other dependency
- com.networknt.petstore.domain.PetRepository:
  - com.networknt.petstore.domain.PetRepositoryJdbc
- com.networknt.petstore.service.PetService:
  - com.networknt.petstore.service.PetServiceImpl
  # HandlerProvider implementation
- com.networknt.petstore.handler.HandlerProvider:
  - com.networknt.petstore.handler.PathPetHandlerProvider