singletons:
  - javax.sql.DataSource:
      - com.zaxxer.hikari.HikariDataSource:
          jdbcUrl: 'jdbc:postgresql://localhost:5432/petstore'
          username: postgres
          password: ''
          maximumPoolSize: 95
  - com.networknt.petstore.domain.PetRepository:
      - com.networknt.petstore.domain.PetRepositoryJdbc
  - com.networknt.petstore.service.PetService:
      - com.networknt.petstore.service.PetServiceImpl
  - com.networknt.registry.URL:
      - com.networknt.registry.URLImpl:
          parameters:
            com.networknt.pet-1.0.0: 'https://localhost:8445'
  - com.networknt.registry.Registry:
      - com.networknt.registry.support.DirectRegistry
  - com.networknt.balance.LoadBalance:
      - com.networknt.balance.RoundRobinLoadBalance
  - com.networknt.cluster.Cluster:
      - com.networknt.cluster.LightCluster
  - com.networknt.petstore.handler.HandlerProvider:
      - com.networknt.petstore.handler.PathPetHandlerProvider
