singletons:
  - javax.sql.DataSource:
      - com.zaxxer.hikari.HikariDataSource:
          jdbcUrl: 'jdbc:postgresql://localhost:5432/petstore'
          username: postgres
          password: ''
          maximumPoolSize: 95
  - com.networknt.petstore.domain.OrderRepository:
      - com.networknt.petstore.domain.OrderRepositoryJdbc
  - com.networknt.petstore.service.OrderService:
      - com.networknt.petstore.service.OrderServiceImpl
  - com.networknt.registry.URL:
      - com.networknt.registry.URLImpl:
          protocol: light
          host: localhost
          port: 8500
          path: consul
          parameters:
            registryRetryPeriod: '30000'
  - com.networknt.consul.client.ConsulClient:
      - com.networknt.consul.client.ConsulClientImpl
  - com.networknt.registry.Registry:
      - com.networknt.consul.ConsulRegistry
  - com.networknt.balance.LoadBalance:
      - com.networknt.balance.RoundRobinLoadBalance
  - com.networknt.cluster.Cluster:
      - com.networknt.cluster.LightCluster
