# Singleton service factory configuration/IoC injection
singletons:

- javax.sql.DataSource:
  - com.zaxxer.hikari.HikariDataSource:
      jdbcUrl: "jdbc:postgresql://localhost:5432/petstore"
      username: postgres
      password: ""
      maximumPoolSize: 95
  # MapConsumerRepository implements CustomerRepository with no other dependency
- com.networknt.petstore.domain.OrderRepository:
  - com.networknt.petstore.domain.OrderRepositoryJdbc
- com.networknt.petstore.service.OrderService:
  - com.networknt.petstore.service.OrderServiceImpl


