singletons:
  - javax.sql.DataSource:
      - com.zaxxer.hikari.HikariDataSource:
          jdbcUrl: 'jdbc:postgresql://localhost:5432/petstore'
          username: postgres
          password: ''
          maximumPoolSize: 95
  - com.networknt.petstore.domain.OrderRepository:
      - com.networknt.petstore.domain.OrderRepositoryJdbc
  - com.networknt.petstore.service.OrderService:
      - com.networknt.petstore.service.OrderServiceImpl
  - com.networknt.registry.URL:
      - com.networknt.registry.URLImpl:
          parameters:
            com.networknt.ab-1.0.0: 'https://localhost:8444'
  - com.networknt.registry.Registry:
    - com.networknt.registry.support.DirectRegistry
  - com.networknt.balance.LoadBalance:
    - com.networknt.balance.RoundRobinLoadBalance
  - com.networknt.cluster.Cluster:
    - com.networknt.cluster.LightCluster
